theme: jekyll-theme-minimal
title: Trefor W. Evans
description: PhD candidate at the University of Toronto conducting Machine Learning research on scalable Gaussian Processes and Bayesian methods for big data.
