#theme: jekyll-theme-minimal
title: Trefor W. Evans
description: PhD candidate at the University of Toronto researching scalable Gaussian Processes and Bayesian methods for big data.
logo: /imgs/trefor.jpg
